# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: route_guide.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'route_guide.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11route_guide.proto\x12\nrouteguide\"\x07\n\x05Point\"\x0b\n\tRectangle\"\t\n\x07\x46\x65\x61ture\"\x0b\n\tRouteNote\"\x0e\n\x0cRouteSummary2\x0c\n\nRouteGuideB6\n\x1bio.grpc.examples.routeguideB\x0fRouteGuideProtoP\x01\xa2\x02\x03RTGb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'route_guide_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033io.grpc.examples.routeguideB\017RouteGuideProtoP\001\242\002\003RTG'
  _globals['_POINT']._serialized_start=33
  _globals['_POINT']._serialized_end=40
  _globals['_RECTANGLE']._serialized_start=42
  _globals['_RECTANGLE']._serialized_end=53
  _globals['_FEATURE']._serialized_start=55
  _globals['_FEATURE']._serialized_end=64
  _globals['_ROUTENOTE']._serialized_start=66
  _globals['_ROUTENOTE']._serialized_end=77
  _globals['_ROUTESUMMARY']._serialized_start=79
  _globals['_ROUTESUMMARY']._serialized_end=93
  _globals['_ROUTEGUIDE']._serialized_start=95
  _globals['_ROUTEGUIDE']._serialized_end=107
# @@protoc_insertion_point(module_scope)
